### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by sharifyounes** [click-contrib/click-didyoumean#12]
Just FYI — my builds started breaking when you pushed 0.2.0.

Celery 5.1.2 requires `click>=7.0,<8.0` and `click-didyoumean>=0.0.3`. But click-didyoumean 0.2.0 now requires `click>=8.0.1`.

Solved by specifying earlier version, `click-didyoumean==0.0.3`.

**Comment by timofurrer** [comment]
I've fixed it in v0.3.0 which requires click >= 7
