### ISSUE TITLE
black requirement too restrictive

### ISSUE THREAD

**Issue by Paul-Durrant** [click-contrib/click-didyoumean#15]
The requirement for black is

`black = "^21.9b0"`

Since black is now on 23.*, and will no doubt be on 24.* next year, perhaps this requirement should be a >= instead of ^:

`black = ">=21.9b0"`

**Comment by sisp** [comment]
The compatible release specifier is even semantically incorrect for Black because Black uses CalVer while `^` is based on the semantics of SemVer.
