### ISSUE TITLE
Please make a new release so that there's something on the PyPI page

### ISSUE THREAD

**Issue by jwodder** [click-contrib/click-didyoumean#17]
Currently, [this project's page on PyPI](https://pypi.org/project/click-didyoumean/) has no useful information — no documentation, not even a link to the repository.  This was fixed locally in a commit made after the latest release, but no release has been made since to improve the project page.  Even if there have been no code changes since the last release, you can still make a [post release](https://peps.python.org/pep-0440/#post-releases) (e.g., version `0.3.0.post1`) so that the updated metadata gets displayed on PyPI.

**Comment by timofurrer** [comment]
It finally happened: https://pypi.org/project/click-didyoumean/ 🎉
