### ISSUE TITLE
Licensing mismatch

### ISSUE THREAD

**Issue by jayvdb** [click-contrib/click-didyoumean#3]
The setup.py metadata says BSD, but the LICENSE is MIT.

**Comment by jayvdb** [comment]
Also a MANIFEST.in with the LICENSE and including the tests would be great.

packaged at https://build.opensuse.org/package/show/home:jayvdb:pipenv-status-check/python-click-didyoumean

**Comment by timofurrer** [comment]
Good catch! Thank you :tada:
